name: "Continuous Deployment (NodeJS)"

on:
  push:
    paths:
      - 'nodejs/**'
    branches:
      - main

  pull_request:
    paths:
      - 'nodejs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-${{ matrix.container }}-${{ hashFiles('**/package.json') }}

      - name: Install Root Dependencies
        run: |
          npm install --ignore-scripts
          npm install -g copyfiles bestzip
        working-directory: nodejs

      - name: Build
        run: npm run build
        working-directory: nodejs

      - name: Pack layer
        run: copyfiles 'node_modules/**' build/workspace/nodejs && copyfiles -f 'scripts/*' build/workspace && copyfiles -f 'build/src/*' build/workspace && cd build/workspace && bestzip ../otel-telescope-layer-nodejs.zip *
        working-directory: nodejs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: bash ./scripts/publish_layer
        working-directory: nodejs
