name: "Continuous Deployment (NodeJS)"

on:
  push:
    paths:
      - 'nodejs/**'
    branches:
      - main

  pull_request:
    paths:
      - 'nodejs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          npm install
          npm install bestzip copyfiles rimraf
          copyfiles 'node_modules/**' build/workspace/nodejs && copyfiles -f 'scripts/*' build/workspace && copyfiles -f 'build/src/*' build/workspace && cd build/workspace && bestzip ../cisco-otel-lambda.zip *
        working-directory: nodejs

  publish-layers:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: ./scripts/publish_layer.sh
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        working-directory: nodejs
