name: "Continuous Deployment (NodeJS)"

on:
  push:
    paths:
      - 'nodejs/**'
    branches:
      - main

  pull_request:
    paths:
      - 'nodejs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-${{ matrix.container }}-${{ hashFiles('**/package.json') }}

      - name: Install Root Dependencies
        run: |
          npm install --ignore-scripts
          npm install -g copyfiles bestzip
        working-directory: nodejs

      - name: Build
        run: npm run build
        working-directory: nodejs

      - name: Pack layer
        run: copyfiles 'node_modules/**' build/workspace/nodejs && copyfiles -f 'scripts/*' build/workspace && copyfiles -f 'build/src/*' build/workspace && cd build/workspace && bestzip ../cisco-otel-lambda.zip *
        working-directory: nodejs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: sh
      - run: ./scripts/publish_layer.sh
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        working-directory: nodejs
